/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cal_cient;

/**
 *
 * @author cmrocha
 */
public class clc extends javax.swing.JFrame {
    double num1, num2,pr, f;
    char letra;
    //int n; 
    //double [] array = new double  [100] ; 
    boolean sum, res, mult, div, porc, raiz, pi,fact, pot, sin, cos, tan, sin_o, cos_o,tan_o, log, ln,deci;       
    String del;
            
            
    /**
     * Creates new form clc
     */
    public clc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clc_display = new javax.swing.JTextField();
        btn_log = new javax.swing.JButton();
        btn_fact = new javax.swing.JButton();
        btn_pot = new javax.swing.JButton();
        btn_rc = new javax.swing.JButton();
        btn_ln = new javax.swing.JButton();
        btn_sin = new javax.swing.JButton();
        btn_cos = new javax.swing.JButton();
        btn_tan = new javax.swing.JButton();
        btn_sininv = new javax.swing.JButton();
        btn_cosinv = new javax.swing.JButton();
        btn_taninv = new javax.swing.JButton();
        btn_pi = new javax.swing.JButton();
        nm_2 = new javax.swing.JButton();
        nm_3 = new javax.swing.JButton();
        btn_del = new javax.swing.JButton();
        nm_1 = new javax.swing.JButton();
        nm_5 = new javax.swing.JButton();
        nm_6 = new javax.swing.JButton();
        btn_mult = new javax.swing.JButton();
        nm_4 = new javax.swing.JButton();
        nm_8 = new javax.swing.JButton();
        nm_9 = new javax.swing.JButton();
        btn_sum = new javax.swing.JButton();
        nm_7 = new javax.swing.JButton();
        nm_0 = new javax.swing.JButton();
        btn_igual = new javax.swing.JButton();
        btn_deci = new javax.swing.JButton();
        btn_c = new javax.swing.JButton();
        btn_div = new javax.swing.JButton();
        btn_res = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        clc_display.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        clc_display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        clc_display.setText("0");
        clc_display.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        clc_display.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        clc_display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clc_displayActionPerformed(evt);
            }
        });
        clc_display.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                clc_displayKeyTyped(evt);
            }
        });

        btn_log.setBackground(new java.awt.Color(51, 51, 51));
        btn_log.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_log.setForeground(new java.awt.Color(255, 255, 255));
        btn_log.setText("Log");
        btn_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logActionPerformed(evt);
            }
        });

        btn_fact.setBackground(new java.awt.Color(51, 51, 51));
        btn_fact.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_fact.setForeground(new java.awt.Color(255, 255, 255));
        btn_fact.setText("x!");
        btn_fact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_factActionPerformed(evt);
            }
        });

        btn_pot.setBackground(new java.awt.Color(51, 51, 51));
        btn_pot.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_pot.setForeground(new java.awt.Color(255, 255, 255));
        btn_pot.setText("x^n");
        btn_pot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_potActionPerformed(evt);
            }
        });

        btn_rc.setBackground(new java.awt.Color(51, 51, 51));
        btn_rc.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_rc.setForeground(new java.awt.Color(255, 255, 255));
        btn_rc.setText(" √ ");
        btn_rc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rcActionPerformed(evt);
            }
        });

        btn_ln.setBackground(new java.awt.Color(51, 51, 51));
        btn_ln.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_ln.setForeground(new java.awt.Color(255, 255, 255));
        btn_ln.setText("Ln");
        btn_ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lnActionPerformed(evt);
            }
        });

        btn_sin.setBackground(new java.awt.Color(51, 51, 51));
        btn_sin.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_sin.setForeground(new java.awt.Color(255, 255, 255));
        btn_sin.setText("Sin");
        btn_sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sinActionPerformed(evt);
            }
        });

        btn_cos.setBackground(new java.awt.Color(51, 51, 51));
        btn_cos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_cos.setForeground(new java.awt.Color(255, 255, 255));
        btn_cos.setText("Cos");
        btn_cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cosActionPerformed(evt);
            }
        });

        btn_tan.setBackground(new java.awt.Color(51, 51, 51));
        btn_tan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_tan.setForeground(new java.awt.Color(255, 255, 255));
        btn_tan.setText("Tan");
        btn_tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tanActionPerformed(evt);
            }
        });

        btn_sininv.setBackground(new java.awt.Color(51, 51, 51));
        btn_sininv.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_sininv.setForeground(new java.awt.Color(255, 255, 255));
        btn_sininv.setText("Sin-1");
        btn_sininv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sininvActionPerformed(evt);
            }
        });

        btn_cosinv.setBackground(new java.awt.Color(51, 51, 51));
        btn_cosinv.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_cosinv.setForeground(new java.awt.Color(255, 255, 255));
        btn_cosinv.setText("Cos-1");
        btn_cosinv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cosinvActionPerformed(evt);
            }
        });

        btn_taninv.setBackground(new java.awt.Color(51, 51, 51));
        btn_taninv.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_taninv.setForeground(new java.awt.Color(255, 255, 255));
        btn_taninv.setText("Tan-1");
        btn_taninv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_taninvActionPerformed(evt);
            }
        });

        btn_pi.setBackground(new java.awt.Color(51, 51, 51));
        btn_pi.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_pi.setForeground(new java.awt.Color(255, 255, 255));
        btn_pi.setText("π");
        btn_pi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_piActionPerformed(evt);
            }
        });

        nm_2.setBackground(new java.awt.Color(204, 255, 255));
        nm_2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nm_2.setText("2");
        nm_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nm_2ActionPerformed(evt);
            }
        });

        nm_3.setBackground(new java.awt.Color(204, 255, 255));
        nm_3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nm_3.setText("3");
        nm_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nm_3ActionPerformed(evt);
            }
        });

        btn_del.setBackground(new java.awt.Color(153, 0, 0));
        btn_del.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_del.setForeground(new java.awt.Color(255, 255, 255));
        btn_del.setText("DEL");
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });

        nm_1.setBackground(new java.awt.Color(204, 255, 255));
        nm_1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nm_1.setText("1");
        nm_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nm_1ActionPerformed(evt);
            }
        });

        nm_5.setBackground(new java.awt.Color(204, 255, 255));
        nm_5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nm_5.setText("5");
        nm_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nm_5ActionPerformed(evt);
            }
        });

        nm_6.setBackground(new java.awt.Color(204, 255, 255));
        nm_6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nm_6.setText("6");
        nm_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nm_6ActionPerformed(evt);
            }
        });

        btn_mult.setBackground(new java.awt.Color(204, 255, 255));
        btn_mult.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_mult.setText("X");
        btn_mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multActionPerformed(evt);
            }
        });

        nm_4.setBackground(new java.awt.Color(204, 255, 255));
        nm_4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nm_4.setText("4");
        nm_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nm_4ActionPerformed(evt);
            }
        });

        nm_8.setBackground(new java.awt.Color(204, 255, 255));
        nm_8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nm_8.setText("8");
        nm_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nm_8ActionPerformed(evt);
            }
        });

        nm_9.setBackground(new java.awt.Color(204, 255, 255));
        nm_9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nm_9.setText("9");
        nm_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nm_9ActionPerformed(evt);
            }
        });

        btn_sum.setBackground(new java.awt.Color(204, 255, 255));
        btn_sum.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_sum.setText("+");
        btn_sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumActionPerformed(evt);
            }
        });

        nm_7.setBackground(new java.awt.Color(204, 255, 255));
        nm_7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nm_7.setText("7");
        nm_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nm_7ActionPerformed(evt);
            }
        });

        nm_0.setBackground(new java.awt.Color(204, 255, 255));
        nm_0.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nm_0.setText("0");
        nm_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nm_0ActionPerformed(evt);
            }
        });

        btn_igual.setBackground(new java.awt.Color(204, 255, 255));
        btn_igual.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_igual.setText("=");
        btn_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_igualActionPerformed(evt);
            }
        });

        btn_deci.setBackground(new java.awt.Color(204, 255, 255));
        btn_deci.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_deci.setText(".");
        btn_deci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deciActionPerformed(evt);
            }
        });

        btn_c.setBackground(new java.awt.Color(153, 0, 0));
        btn_c.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_c.setForeground(new java.awt.Color(255, 255, 255));
        btn_c.setText("C");
        btn_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cActionPerformed(evt);
            }
        });

        btn_div.setBackground(new java.awt.Color(204, 255, 255));
        btn_div.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_div.setText("/");
        btn_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divActionPerformed(evt);
            }
        });

        btn_res.setBackground(new java.awt.Color(204, 255, 255));
        btn_res.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_res.setText("-");
        btn_res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("e");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(nm_4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(nm_5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(nm_6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_mult, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(nm_1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(nm_2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(nm_3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nm_7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nm_8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nm_9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_sum, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nm_0, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(btn_igual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_div, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_c, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_res, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_deci, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clc_display, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_log, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_fact, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_pot, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn_sin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_cos, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_tan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_rc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_sininv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_ln, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                    .addComponent(btn_cosinv, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_pi, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                    .addComponent(btn_taninv, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(clc_display, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_log)
                    .addComponent(btn_fact)
                    .addComponent(btn_pot)
                    .addComponent(btn_rc)
                    .addComponent(btn_ln)
                    .addComponent(btn_pi))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sin)
                    .addComponent(btn_cos)
                    .addComponent(btn_tan)
                    .addComponent(btn_sininv)
                    .addComponent(btn_cosinv)
                    .addComponent(btn_taninv))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nm_2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nm_3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nm_1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nm_5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nm_6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_mult, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nm_4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nm_8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nm_9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_sum, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nm_7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_c, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_div, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_res, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nm_0, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_deci, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        clc_display.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nm_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nm_1ActionPerformed
        if(clc_display.getText().equals("0")){
           clc_display.setText(" ");
        }
        clc_display.setText(clc_display.getText()+"1");
    }//GEN-LAST:event_nm_1ActionPerformed

    private void nm_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nm_2ActionPerformed
         if(clc_display.getText().equals("0")){
           clc_display.setText(" ");
        }
        clc_display.setText(clc_display.getText()+"2");
    }//GEN-LAST:event_nm_2ActionPerformed

    private void nm_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nm_3ActionPerformed
         if(clc_display.getText().equals("0")){
           clc_display.setText(" ");
        }
        clc_display.setText(clc_display.getText()+"3");
    }//GEN-LAST:event_nm_3ActionPerformed

    private void nm_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nm_4ActionPerformed
          if(clc_display.getText().equals("0")){
           clc_display.setText(" ");
        }
        clc_display.setText(clc_display.getText()+"4");
    }//GEN-LAST:event_nm_4ActionPerformed

    private void nm_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nm_5ActionPerformed
          if(clc_display.getText().equals("0")){
           clc_display.setText(" ");
        }
        clc_display.setText(clc_display.getText()+"5");
    }//GEN-LAST:event_nm_5ActionPerformed

    private void nm_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nm_6ActionPerformed
          if(clc_display.getText().equals("0")){
           clc_display.setText(" ");
        }
        clc_display.setText(clc_display.getText()+"6");
    }//GEN-LAST:event_nm_6ActionPerformed

    private void nm_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nm_7ActionPerformed
          if(clc_display.getText().equals("0")){
           clc_display.setText(" ");
        }
        clc_display.setText(clc_display.getText()+"7");
    }//GEN-LAST:event_nm_7ActionPerformed

    private void nm_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nm_8ActionPerformed
          if(clc_display.getText().equals("0")){
           clc_display.setText(" ");
        }
        clc_display.setText(clc_display.getText()+"8");
    }//GEN-LAST:event_nm_8ActionPerformed

    private void nm_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nm_9ActionPerformed
          if(clc_display.getText().equals("0")){
           clc_display.setText(" ");
        }
        clc_display.setText(clc_display.getText()+"9");
    }//GEN-LAST:event_nm_9ActionPerformed

    private void nm_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nm_0ActionPerformed
          if(clc_display.getText().equals("0")){
           clc_display.setText(" ");
        }
        clc_display.setText(clc_display.getText()+"0");
    }//GEN-LAST:event_nm_0ActionPerformed

    private void btn_multActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multActionPerformed
        mult=true;
       // n = array.length;  
        num1=Double.parseDouble(clc_display.getText());
       // array [n+1] = num1;
        //n=n+1;
        clc_display.setText("0");
    }//GEN-LAST:event_btn_multActionPerformed

    private void btn_sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumActionPerformed
        sum=true;
        num1=Double.parseDouble(clc_display.getText());
        clc_display.setText("0");
    }//GEN-LAST:event_btn_sumActionPerformed

    private void btn_resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resActionPerformed
        res=true;
        num1=Double.parseDouble(clc_display.getText());
        clc_display.setText("0");
    }//GEN-LAST:event_btn_resActionPerformed

    private void btn_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divActionPerformed
        div=true;
        num1=Double.parseDouble(clc_display.getText());
        clc_display.setText("0");
    }//GEN-LAST:event_btn_divActionPerformed

    private void btn_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_igualActionPerformed
        num2=Double.parseDouble(clc_display.getText());
        if(sum==true){
            clc_display.setText(String.valueOf(num1+num2));
        }else if(res==true){
            clc_display.setText(String.valueOf(num1-num2));
        }else if(mult==true){
            clc_display.setText(String.valueOf(num1*num2));
        }else if(div==true){
            clc_display.setText(String.valueOf(num1/num2));
        }else if(pot==true){
            
            clc_display.setText(String.valueOf(Math.pow(num1,num2)));
        }else if(cos==true){
            
            clc_display.setText(String.valueOf(num1));
        }else if(sin==true){
            clc_display.setText(String.valueOf(num1));
        }else if(log==true){
            clc_display.setText(String.valueOf(Math.log10(num1)));
        }else if(tan==true){
            clc_display.setText(String.valueOf(num1));
        }else if(sin_o==true){
            clc_display.setText(String.valueOf(num1));
        }else if(cos_o==true){
            clc_display.setText(String.valueOf(num1));
        }else if(tan_o==true){
            clc_display.setText(String.valueOf(num1));
        }else if(ln==true){
            clc_display.setText(String.valueOf(Math.log(num1)));
        }else if(fact==true){
            clc_display.setText(String.valueOf(f));
        }
        sum=false;
        res=false;
        mult=false;
        div=false;
        pot=false;
        cos=false;
        sin=false;
        log=false;
        tan=false;
        tan_o=false;
        cos_o=false;
        sin_o=false;
        ln=false;
        fact=false;
    }//GEN-LAST:event_btn_igualActionPerformed

    private void btn_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cActionPerformed
        clc_display.setText("0");
    }//GEN-LAST:event_btn_cActionPerformed

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
     del  = clc_display.getText();
     pr=del.length()-1;
     del=del.substring(0,del.length()-1);
     clc_display.setText(del);
    
    }//GEN-LAST:event_btn_delActionPerformed

    private void btn_deciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deciActionPerformed
        if(!clc_display.getText().contains(".")){
            clc_display.setText(clc_display.getText()+".");
            deci=true;
        }
    }//GEN-LAST:event_btn_deciActionPerformed

    private void btn_rcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rcActionPerformed
        raiz=true;
        num1=Double.parseDouble(clc_display.getText());
       // display.setText("0");
        clc_display.setText(String.valueOf(Math.sqrt(num1)));
    }//GEN-LAST:event_btn_rcActionPerformed

    private void btn_potActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_potActionPerformed
        pot=true;
        num1=Double.parseDouble(clc_display.getText());
        clc_display.setText("0");
    }//GEN-LAST:event_btn_potActionPerformed

    private void btn_cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cosActionPerformed
        cos=true;
        //clc_display.setText("Cos");
        num1=Double.parseDouble(clc_display.getText());
        num1=Math.toRadians(num1);
        num1= Math.cos(num1);
        
    }//GEN-LAST:event_btn_cosActionPerformed

    private void btn_cosinvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cosinvActionPerformed
      cos_o=true;
      num1=Double.parseDouble(clc_display.getText());
      num1=Math.acos(Math.toRadians(num1));
    }//GEN-LAST:event_btn_cosinvActionPerformed

    private void btn_sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sinActionPerformed
      sin=true;
      num1=Double.parseDouble(clc_display.getText());
      num1=Math.sin(Math.toRadians(num1));
    }//GEN-LAST:event_btn_sinActionPerformed

    private void btn_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logActionPerformed
        log = true;
        num1= Double.parseDouble(clc_display.getText());
        
    }//GEN-LAST:event_btn_logActionPerformed

    private void btn_tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tanActionPerformed
      tan=true;
      num1=Double.parseDouble(clc_display.getText());
      num1=Math.tan(Math.toRadians(num1));
    }//GEN-LAST:event_btn_tanActionPerformed

    private void btn_sininvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sininvActionPerformed
      sin_o=true;
      num1=Double.parseDouble(clc_display.getText());
      num1=Math.asin(Math.toRadians(num1));
    }//GEN-LAST:event_btn_sininvActionPerformed

    private void btn_taninvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_taninvActionPerformed
      tan_o=true;
      num1=Double.parseDouble(clc_display.getText());
      num1=Math.atan(Math.toRadians(num1));
    }//GEN-LAST:event_btn_taninvActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(clc_display.getText().equals("0")){
           clc_display.setText(" ");
        }
        clc_display.setText(clc_display.getText()+"2.71828");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_piActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_piActionPerformed
        if(clc_display.getText().equals("0")){
           clc_display.setText(" ");
        }
        clc_display.setText(clc_display.getText()+"3.14159");
    }//GEN-LAST:event_btn_piActionPerformed

    private void btn_lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lnActionPerformed
        ln = true;
        num1= Double.parseDouble(clc_display.getText());
    }//GEN-LAST:event_btn_lnActionPerformed

    private void btn_factActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_factActionPerformed
        fact=true;
        num1= Double.parseDouble(clc_display.getText());
        f=1;
        for (int i = 1; i <= num1; i++) {
            f = f * i;
        }
        
    }//GEN-LAST:event_btn_factActionPerformed

    private void clc_displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clc_displayActionPerformed
        // TODO add your handling code her
    }//GEN-LAST:event_clc_displayActionPerformed

    private void clc_displayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clc_displayKeyTyped
        letra = evt.getKeyChar();
        if (letra < 0 || letra > 9 ) {
            evt.consume();
        }
    }//GEN-LAST:event_clc_displayKeyTyped

    /**
     * @param args the command line 
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_c;
    private javax.swing.JButton btn_cos;
    private javax.swing.JButton btn_cosinv;
    private javax.swing.JButton btn_deci;
    private javax.swing.JButton btn_del;
    private javax.swing.JButton btn_div;
    private javax.swing.JButton btn_fact;
    private javax.swing.JButton btn_igual;
    private javax.swing.JButton btn_ln;
    private javax.swing.JButton btn_log;
    private javax.swing.JButton btn_mult;
    private javax.swing.JButton btn_pi;
    private javax.swing.JButton btn_pot;
    private javax.swing.JButton btn_rc;
    private javax.swing.JButton btn_res;
    private javax.swing.JButton btn_sin;
    private javax.swing.JButton btn_sininv;
    private javax.swing.JButton btn_sum;
    private javax.swing.JButton btn_tan;
    private javax.swing.JButton btn_taninv;
    private javax.swing.JTextField clc_display;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton nm_0;
    private javax.swing.JButton nm_1;
    private javax.swing.JButton nm_2;
    private javax.swing.JButton nm_3;
    private javax.swing.JButton nm_4;
    private javax.swing.JButton nm_5;
    private javax.swing.JButton nm_6;
    private javax.swing.JButton nm_7;
    private javax.swing.JButton nm_8;
    private javax.swing.JButton nm_9;
    // End of variables declaration//GEN-END:variables
}
